### ISSUE TITLE
Cannot build against accumulo 2.0 because thrift packages changed

### ISSUE THREAD

**Issue by phrocker** [phrocker/sharkbite#18]
since the package names in accumulo 2.x took a different name (clientImpl vs client::impl ) this requires a way to alias namespaces and/or packages. Without these changes we could have a client that communicates with 1.x and 2.x seamlessly; however, as 2.0 has already been released we will need to accommodate this gracefully.  

Curious @keith-turner can you shed some light on if this was a necessary change? Sorry I didn't see this sooner, but this C++ namespace casing is unconventional ( with some non commercial compilers that has been a problem in the past I don't know if that is still the case). I *think* I can solve this locally by naming those packages myself, as long as these packages aren't serialized in some way I should be fine.

**Comment by keith-turner** [comment]
> Curious @keith-turner can you shed some light on if this was a necessary change?

The intent with the change was to simplify Accumulo's public API definition for 2.0.  The public API used to be a list of packages, with a list of sub-packages to exclude. Now its just a list of packages.  Also, had anyone been using non api packages in 1.9 there was a very good changes their code would have broken anyway because 2.0 had so many internal changes (client context, table id type, etc).  So it seemed like a good time to make this change.

> I think I can solve this locally by naming those packages myself, as long as these packages aren't serialized in some way I should be fine.

I think you may be right about that.  My memory is a bit fuzzy because I did this months ago.  I did upgrade testing, and during those test I think I connected a 1.9 client to a 2.0 server (or maybe visa-versa) and  think it mostly worked.   I think for RPC purposes the package names are not used, only the type names.  So your client can use whatever package names it likes and it may work as long as the type names are the same.

**Comment by phrocker** [comment]
@keith-turner Thanks! To be clear I was referencing the c++ namespace of clientImpl -- which I confirmed fails on some musl variants, but I don't anticipate many using the thrift bindings within their c++ code base -- so I think any problems are minimal. I changed it for my purposes and will begin integrating that. 

Thanks for the insight into 1.9 vs 2.0 . I plan on using the 2.x thrift bindings and have a planned way of abstracting the v1.x and v2.x RPC calls. This allows me to perform all types of operations and detect which version of the server with which I'm communicating. Since thrift is wire format compatible using 0.12.0 works seamlessly across 1.x and 2.x. I still have quite a bit of work to do but I've isolated the RPC footprint so that it's generally based within a single module. 

Appreciate the insight!
