### ISSUE TITLE
[Python] Error when passing None to the pysharkbite.Range

### ISSUE THREAD

**Issue by loomlike** [phrocker/sharkbite#34]
## Description
In pysharkbite, cannot use `None` for the infinite range (equivalent to Java API's null).
If I pass `None` for a key, I get the following error:
```
pysharkbite.Range(None, True, "2", False)

> TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. pysharkbite.Range(arg0: str)
    2. pysharkbite.Range(arg0: pysharkbite.Key, arg1: bool, arg2: pysharkbite.Key, arg3: bool)
    3. pysharkbite.Range(arg0: pysharkbite.Key, arg1: bool)
    4. pysharkbite.Range(arg0: str, arg1: bool, arg2: str, arg3: bool)

Invoked with: None, True, '2', False
```

If I use `start_key = pysharkbite.Key()` without `setRow`,
`scanner.getResultSet()` throws the following error
```
[2019-12-20 22:48:25.782] [interconnect::AccumuloServerFacadeV2] [debug] Error on extenttableId:5 end:< prev:<
 and range is Range [ : []
```
and end_key without `setRow` throws an exception:
```
RuntimeError: Caught an unknown exception!
```

## Package version
0.5.1.2

## Expected behavior
Be able to pass `None` to the start_key and end_key for negative infinity and positive infinity, respectively.

**Comment by phrocker** [comment]
@loomlike ahh I think this is because it can't determine which constructor to use since the two underlying types are string and an object. In the code example, below, there are two tests one which uses the string type and "" works. In the follow on example a Key object is used, which works in the system regression test, provided. 

https://github.com/phrocker/sharkbite/blob/master/test/python/TestRanges.py#L119

There are some things I can do to infer types so I will see what I can do under the guise of this issue

**Comment by loomlike** [comment]
Thank you! I just tested from my end and `""` worked.
I think the simplest way is to check the type of not-None key to determine which function to call.

Feel free to close this issue if you wanted to use None value only for the object based function.
