### ISSUE TITLE
ImportError: dynamic module does not define module export function (PyInit_pysharkbite)

### ISSUE THREAD

**Issue by divgo** [phrocker/sharkbite#53]
when trying to use SharkBite, I am getting the above error when calling
```import pysharkbite```

Sharkbite was built using the following command;

```pip3 install .```

**Comment by phrocker** [comment]
hi @divgo , I would advise using the pypi distribution. ( https://pypi.org/project/sharkbite/ )  just do pip3 install sharkbite and pull it from there. 

If you want to build it from root, then can you tell me what distro you are using and version of gcc?  Happy to help if you want to go that route.

**Comment by phrocker** [comment]
Here is an example using sharkbite from pypi https://github.com/phrocker/Jangowave

**Comment by divgo** [comment]
Confirmed. When I install via `pip install sharkbite` - it works. 
I would like to be able to use the Iterators support, so that is why I was trying to build from sources. 

here is my Dockerfile;

```FROM gcc:9

RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - \
    && curl https://packages.microsoft.com/config/debian/10/prod.list > /etc/apt/sources.list.d/mssql-release.list \
    && git clone -b master https://github.com/phrocker/sharkbite.git /sharkbite

#Install MSSQL ODBC and dependencies for PyODBC
RUN apt-get update && \
    apt-get install -y \
    cmake \
    # build-essential \
    # libboost-dev \
    # libboost-thread-dev \
    # libboost-date-time-dev \
    # libboost-atomic-dev \
    # libboost-chrono-dev \
    # libboost-system-dev \
    # libboost-regex-dev \
    python3.7 \
    python3-pip \
    sudo \
    tdsodbc \
    unixodbc \
    unixodbc-dev \
    && sudo ACCEPT_EULA=Y apt-get -y install msodbcsql17 \
    && apt-get clean -y

WORKDIR /sharkbite

# RUN ls

# RUN cmake . -DPYTHON_ITERATOR_SUPPORT="ON" # this fails 
# \
# && cmake --build . ;
# RUN pip install . && \
#     pip install \
#     azure_storage_blob \
#     future \
#     prometheus_client \
#     pyodbc

RUN pip3 install sharkbite && \
    pip3 install \
    azure_storage_blob \
    future \
    prometheus_client \
    pyodbc
# --install-option='-DPYTHON_ITERATOR_SUPPORT=ON' .
# RUN gcc -o myapp main.c
CMD ["./sharkbite"]```

**Comment by phrocker** [comment]
@divgo  Sorry that the JAR isn't in maven central yet. When that's complete ( soon ) you should simply be able to download it. I've updated the instructions on the Readme. I've switched to using Jython since it doesn't require rebuilding the C++ code. It also loses only a tiny bit of performance for the benefit of increased stability. Here is an example Dockerfile I just tested successfully.

`FROM debian:buster

 RUN apt-get update && \
      apt-get install -y \
      curl git \
      gnupg gnupg2
RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - \
    && curl https://packages.microsoft.com/config/debian/10/prod.list > /etc/apt/sources.list.d/mssql-release.list \
    && git clone -b master https://github.com/phrocker/sharkbite.git /sharkbite

#Install MSSQL ODBC and dependencies for PyODBC
RUN apt-get update && \
    apt-get install -y \
    maven \
    python3.7-dev \
    openjdk-11-jdk \
    python3-pip \
    sudo \
    tdsodbc \
    unixodbc \
    unixodbc-dev \
    && sudo ACCEPT_EULA=Y apt-get -y install msodbcsql17 \
    && apt-get clean -y

WORKDIR /sharkbite/native-iterators-jni

 RUN ls

RUN mvn package -DskipTests

RUN pip3 install sharkbite && \
    pip3 install \
    azure_storage_blob \
    future \
    prometheus_client \
    pyodbc
# --install-option='-DPYTHON_ITERATOR_SUPPORT=ON' .
# RUN gcc -o myapp main.c
CMD ["./sharkbite"]```
`

**Comment by phrocker** [comment]
You could probably remove some of the extra inclusions but the big thing is that openjdk-11-jdk was needed. You can change that to 8. Sorry for not making that more clear. I also added python3.7-dev, but that would only be needed if building from cmake. Since you just want the JAR that isn't necessary.

**Comment by phrocker** [comment]
I believe this is solved.
